config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'books' => 'books#index'
  post 'books' =>'books#create'
  get 'books/:id/edit' => 'books#edit' ,as: 'edit_book'
  patch 'books/:id' => 'books#update', as:'update_book'
  get 'books/:id' => 'books#show' ,as:'book'
  get 'books/new'
  delete 'books/:id' => 'books#destroy' ,as: 'destroy_book'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new

    @books =Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update_successfully] ="Book was successfully updated"
      redirect_to book_path(@book[:id])
    else
      render :edit
    end


  end

  def show
    @book = Book.find(params[:id])
  end

  def new

  end
  def create
      @book = Book.new(book_params)
      @books = Book.all

      if @book.save
        flash[:create_successfully] ="Book was successfully created"
        redirect_to book_path(@book.id)
      else
        render :index
      end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:destroy_successfully] = "Book was successfully destroyed"
    redirect_to '/books'
  end
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <div class ="error_msgs_form">
      <div class ="error_msgs_main">
        <% if @book.errors.count == 1%>
          <h2> 1 error prohibited this book from being saved.</h2>
        <% else %>
          <h2> 2 errors prohibited this book from being saved.</h2>
        <% end %>
      </div>

      <ul class ="error_msgs_detail">
        <% @book.errors.full_messages.each do |message| %>
          <li> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <%= form_with model: @book do |f|%>

    <div class ="field_with_errors">
      <label for ="book_title">Title</label>
      <%= f.text_field :title %>
    </div>

    <div class ="field_with_errors">
      <label for ="book_body">Body</label>
      <%= f.text_area :body %>
    </div>

    <div class ="action">
      <%= f.submit 'Update Book' %>
    </div>

  <% end %>
<% else %>

  <%= form_with model: @book do |f|%> <%#通常時に表示されるもの%>

    <div class ="field">
      <label for ="book_title">Title</label>
      <%= f.text_field :title %>
    </div>

    <div class ="field">
      <label for ="book_body">Body</label>
      <%= f.text_area :body %>
    </div>

    <div class ="action">
      <%= f.submit 'Update Book' %>
    </div>

  <% end %>
<% end %>

<%= link_to "Show", "/books/#{@book.id}" %> | <%= link_to "Back" , "/books" %>

app/views/books/index.html.erb
<p id ="notice">
  <%= flash[:destroy_successfully] %>
</p>

<%# ここからインデックス作る予定%>

<h1>Books</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
    <tbody>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", "/books/#{book.id}" %></td>
        <td><%= link_to "Edit", "/books/#{book.id}/edit" %></td>
        <td><%= link_to "Destroy", destroy_book_path(book[:id]), method: :delete,"data-confirm" => "Are you sure?" %></td>
      </tr>
    </tbody>
  <% end %>
</table>


<%# ここから投稿フォームの作成%>
<h2>New book</h2>

<% if @book.errors.any? %> <%# 以下エラー分が表示された時のやつ。%>
  <div class ="error_msgs_form">
    <div class ="error_msgs_main">
        <% if @book.errors.count == 1%>
          <h2> 1 error prohibited this book from being saved.</h2>
        <% else %>
          <h2> 2 errors prohibited this book from being saved.</h2>
        <% end %>
    </div>

    <ul class ="error_msgs_detail">
      <% @book.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
  </div>



  <%= form_with model: @book do |f| %>
    <div class ="field_with_errors">
      <label for ="book_title">Title</label>
      <%= f.text_field :title %>
    </div>

    <div class ="field_with_errors">
      <label for ="book_body">Body</label>
      <%= f.text_area :body %>
    </div>

    <div class ="action">
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>



<% else %>
  <%= form_with model: @book do |f| %> <%#　デフォルトの表示の際に使うもの %>
    <div class ="field">
      <label for ="book_title">Title</label>
      <%= f.text_field :title %>
    </div>

    <div class ="field">
      <label for ="book_body">Body</label>
      <%= f.text_area :body %>
    </div>

    <div class ="action">
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>
<% end %>

app/views/books/new.html.erb
aaaa

app/views/books/show.html.erb
<p id="notice">
    <%= flash[:update_successfully] %>
    <%= flash[:create_successfully] %>
</p>

<p><strong>Title: </strong><%= @book.title %></p>

<p><strong>Body: </strong><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %> | <%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p><strong>Bookers</strong>では、様々な書籍やに関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

<p><a href ="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>